[execute.py]
  [test_abort_by_user_prompt_twice[alert\]]
    expected: FAIL
    disabled: Bug 1459118

  [test_abort_by_user_prompt_twice[confirm\]]
    expected: FAIL
    disabled: Bug 1459118

  [test_abort_by_user_prompt_twice[prompt\]]
    expected: FAIL
    disabled: Bug 1459118

